In [1]:
import matplotlib.pyplot as plt


import torch
import torch.nn as nn
import torchvision
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [2]:
#Own Code
from privacyflow.datasets import faces_dataset

In [3]:
#Check if GPU is available
if torch.cuda.is_available():
    print("GPU will be used")
    device = torch.device('cuda')
else:
    print("No GPU available")
    device = torch.device('cpu')

No GPU available


In [4]:
train_data = faces_dataset.FacesDataset(mode = "train")


In [10]:
img = train_data[0]
torchvision.transforms.ToPILImage()(img).show()

In [17]:
img.shape

torch.Size([3, 218, 178])

In [16]:
img

tensor([[[253, 253, 253,  ..., 247, 254, 254],
         [253, 253, 253,  ..., 249, 254, 254],
         [253, 253, 253,  ..., 250, 255, 255],
         ...,
         [140, 116, 146,  ..., 122, 122, 122],
         [130, 138, 166,  ..., 118, 118, 118],
         [168, 204, 245,  ..., 118, 120, 120]],

        [[231, 231, 231,  ..., 226, 238, 238],
         [231, 231, 231,  ..., 228, 238, 238],
         [231, 231, 231,  ..., 231, 239, 239],
         ...,
         [ 74,  48,  78,  ...,  55,  56,  56],
         [ 62,  70,  98,  ...,  49,  51,  51],
         [100, 136, 177,  ...,  49,  50,  50]],

        [[194, 194, 194,  ..., 225, 222, 222],
         [194, 194, 194,  ..., 225, 222, 222],
         [194, 194, 194,  ..., 227, 223, 223],
         ...,
         [ 26,   1,  33,  ...,  28,  30,  30],
         [ 15,  23,  53,  ...,  20,  24,  24],
         [ 53,  89, 132,  ...,  20,  24,  24]]], dtype=torch.uint8)

In [20]:
test = torch.empty(3,4,2)

In [21]:
test

tensor([[[9.4592e-39, 1.0102e-38],
         [2.9389e-39, 1.0194e-38],
         [1.0102e-38, 9.2755e-39],
         [1.0102e-38, 9.0919e-39]],

        [[1.0653e-38, 1.0561e-38],
         [9.3674e-39, 1.0469e-38],
         [2.9389e-39, 1.0745e-38],
         [9.4592e-39, 9.3674e-39]],

        [[9.5512e-39, 1.0653e-38],
         [1.0928e-38, 1.0469e-38],
         [9.2755e-39, 1.5414e-43],
         [0.0000e+00, 0.0000e+00]]])

In [1]:
from privacyflow.preprocessing import sleep_preprocess
sleep_preprocess.preprocess_sleep_data()

In [2]:
import pandas as pd
from privacyflow.configs import path_configs
pd.read_csv(path_configs.SLEEP_DATA_PREP_TRAIN)

Gender  Age  Sleep Duration  Quality of Sleep  Physical Activity Level  \
0         1   38             7.1                 8                      6.0   
1         1   52             8.4                 9                      3.0   
2         0   33             6.0                 6                      3.0   
3         0   38             7.1                 8                      6.0   
4         1   39             8.0                 9                      8.0   
..      ...  ...             ...               ...                      ...   
297       0   33             6.1                 6                      3.0   
298       0   31             6.1                 6                      3.0   
299       1   49             6.2                 6                      9.0   
300       0   39             7.2                 8                      6.0   
301       1   59             8.1                 9                      7.5   

     Stress Level  BMI Category  Heart Rate  Daily Steps  Sleep Disorder  \
0               4             0          68          7.0               0   
1               3             0          65          5.0               0   
2               8             0          72          5.0               0   
3               5             0          68          8.0               0   
4               3             1          67          7.5               0   
..            ...           ...         ...          ...             ...   
297             8             0          72          5.0               0   
298             8             0          72          5.0               0   
299             8             1          75         10.0               0   
300             5             0          68          8.0               0   
301             3             1          68          7.0               0   

     Avg Wage  Blood Pressure - systolic  Blood Pressure - diastolic  
0          85                        115                          75  
1         107                        125                          80  
2         225                        125                          80  
3         160                        130                          85  
4          85                        115                          78  
..        ...                        ...                         ...  
297       225                        125                          80  
298       225                        125                          80  
299        90                        140                          95  
300       160                        130                          85  
301        90                        140                          95  

[302 rows x 13 columns]

In [1]:
#Own Code
from privacyflow.datasets import sleep_dataset
train_data = sleep_dataset.SleepDataset(mode = "train")
tst_inp, tst_lbl = train_data[0]

In [2]:
tst_inp

tensor([  1.0000,  38.0000,   7.1000,   8.0000,   6.0000,   4.0000,   0.0000,
         68.0000,   7.0000,  85.0000, 115.0000,  75.0000], dtype=torch.float64)

In [3]:
tst_lbl

tensor([1, 0, 0])